name: Deploy package

on:
  workflow_dispatch:
  push:
    tags:
    - "v*"

jobs:
  deploy-package:
    environment:
      name: package
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        name: Setup uv
        with:
          enable-cache: true
      - name: Install Python 3.12
        run: uv python install 3.12
      - run: uv build --package autogen_anthropic_client --out-dir dist/
        name: Build package
        working-directory: python
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist/
